import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local'
import { cn } from "@/lib/utils";
import Player from "@/components/player/player";
import Sidebar from "@/components/sidebar/sidebar";
import ModalProvider from "@/providers/modal-provider";

const font = localFont({
    src: '../public/fonts/font.woff2'
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en">
            <body className={font.className}>
                <ModalProvider></ModalProvider>
                <div className={cn('flex h-[calc(100%-88px)]')}>
                    <Sidebar></Sidebar>
                    <main className="h-full flex-1 overflow-y-auto py-2 pr-2">
                        {children}
                    </main>
                </div>
                <div>
                    <Player></Player>
                </div>
            </body>
        </html>
    );
}
